---

Style/IndentationWidth:
    Width: 4

Metrics/ClassLength:
    CountComments: false
    Max: 200

Metrics/LineLength:
    Max: 100
    AllowURI: true
    URISchemes:
        - http
        - https
