---

- name: Fail if invalid architecture
  fail: msg="Invalid node_arch {{ node_arch }} not x86|x64"
  when: node_arch not in ['x86', 'x64']

- name: Download archive {{ node_directory }}/{{ node_tar_file }}
  become: true
  get_url: url="{{ node_url }}" dest="{{ node_directory }}/{{ node_tar_file }}"

# the builtin unarchive doesn't support stripping the top level directory
# this becomes a huge mess if moving/linking directories in a version
# specific subdirectory is required...
- name: Unpack Node archive {{ node_tar_file }}
  become: true
  register: node_tar_result
  failed_when: node_tar_result.rc != 0
  changed_when: node_tar_result.rc == 0
  shell: cd {{ node_directory }} && {{ tar_cmd }} --strip-components=1 --no-same-owner --owner={{ node_owner }} --group={{ node_group }} -Jxf {{ node_tar_file }}
  when: install_node

- debug: var=node_tar_result
  when: install_node and node_tar_result.rc != 0
