---

- name: Import SMF manifest
  become: true
  shell: /usr/sbin/svccfg -v import "{{ smf_directory }}/cosi-site.xml"

- name: Restart Site
  become: true
  service: name="cosi-site" state="restarted"
